version: 0.0
os: linux
files:
  - source:backend
    destination: /home/ec2-user/doctor-backend

hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
